- name: Install Ansible
  pip:
    name: ansible
    executable: pipx

- name: Install AWS CLI tools
  pip: name=awscli extra_args="--ignore-installed six"
  become: yes

- name: Install Vagrant
  homebrew_cask: name=vagrant

- name: Install Google Cloud SDK
  homebrew_cask: name=google-cloud-sdk

- name: Install Terraform
  homebrew: name=terraform

- name: Install bundler
  gem: name=bundler executable=/Users/svo/.rbenv/shims/gem

- name: Install direnv
  homebrew: name=direnv

- name: Install tflint
  homebrew: name=tflint

- name: Install tfenv
  homebrew: name=tfenv

- name: Install terraform-docs
  homebrew: name=terraform-docs

- name: Install Packer
  homebrew: name=packer

- name: Install templates for Kubernetes manifests
  homebrew: name=ktmpl

- name: Install Kuberenetes command line
  homebrew: name=kubernetes-cli

- name: Install Act for testing local GitHub workflows
  homebrew: name=act

- name: Install vim plugins
  git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
  with_items:
    - {repo: "https://github.com/pearofducks/ansible-vim.git", dest: ansible-vim}
    - {repo: "https://github.com/hashivim/vim-terraform.git", dest: vim-terraform}
    - {repo: "https://github.com/rodjek/vim-puppet.git", dest: vim-puppet}
    - {repo: "https://github.com/hashivim/vim-packer.git", dest: vim-packer}
