- name: Install Ansible
  ansible.builtin.pip:
    name: ansible
    executable: pipx
    extra_args: --include-deps

- name: Install Ansible
  ansible.builtin.pip:
    name: ansible-lint
    executable: pipx

- name: Install AWS CLI tools
  ansible.builtin.pip:
    name: awscli
    extra_args: --ignore-installed six
  become: true

- name: Install Vagrant
  community.general.homebrew_cask:
    name: vagrant

- name: Install Google Cloud SDK
  community.general.homebrew_cask:
    name: google-cloud-sdk

- name: Install Terraform
  community.general.homebrew:
    name: terraform

- name: Install bundler
  gem:
    name: bundler
    executable: ~/.rbenv/shims/gem

- name: Install direnv
  community.general.homebrew:
    name: direnv

- name: Install tflint
  community.general.homebrew:
    name: tflint

- name: Install terraform-docs
  community.general.homebrew:
    name: terraform-docs

- name: Install Packer
  community.general.homebrew:
    name: packer

- name: Install templates for Kubernetes manifests
  community.general.homebrew:
    name: ktmpl

- name: Install Kuberenetes command line
  community.general.homebrew:
    name: kubernetes-cli

- name: Install Act for testing local GitHub workflows
  community.general.homebrew:
    name: act

- name: Install vim plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "~/.vim/bundle/{{ item.dest }}"
  with_items:
    - {repo: "https://github.com/pearofducks/ansible-vim.git", dest: ansible-vim}
    - {repo: "https://github.com/hashivim/vim-terraform.git", dest: vim-terraform}
    - {repo: "https://github.com/rodjek/vim-puppet.git", dest: vim-puppet}
    - {repo: "https://github.com/hashivim/vim-packer.git", dest: vim-packer}
