
    - name: Install go
      homebrew: name=go

    - name: Install vim plugin
      git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
      with_items:
      - {repo: "https://github.com/fatih/vim-go.git", name: vim-go}
