---
- hosts: all

  pre_tasks:

    - name: Get brew path
      shell: brew --prefix
      register: brew_path

    - name: Add brew to shell
      lineinfile: path=~/.zprofile line='eval "$({{ brew_path.stdout_lines[0] }}/bin/brew shellenv)"' create=yes

    - name: Install brew versions tap
      shell: brew tap homebrew/cask-versions

    - name: Add /usr/local/sbin to path
      lineinfile: path=/etc/paths line='/usr/local/sbin' insertbefore='/usr/sbin'
      become: yes

    - hostname: name={{ ansible_user_id }}-mac
      become: yes

  roles:

    - source-control
    - docker
    - cli-tools
    - vim
    - python
    - system
    - java
    - gradle
    - maven
    - node
    - clojure
    - golang
    - kotlin
    - ruby
    - flutter
    - android
    - office
    - plantuml
    - atom
    - semgrep
    - security
    - internet
    - infrastructure-as-code
    - media

  post_tasks:

    - name: Change .local ownership and permissions
      file: path={{ brew_path.stdout_lines[0] }}/share owner={{ ansible_user_id }} recurse=yes mode='0755'
      become: yes
