---
- hosts: all

  pre_tasks:

    - name: Add brew to shell
      lineinfile: path=~/.zprofile line='eval "$(/opt/homebrew/bin/brew shellenv)"' create=yes

    - name: Install brew versions tap
      shell: /opt/homebrew/bin/brew tap homebrew/cask-versions

    - name: Add drivers brew tap
      shell: /opt/homebrew/bin/brew tap homebrew/cask-drivers

    - name: Add /usr/local/sbin to path
      lineinfile: path=/etc/paths line='/usr/local/sbin' insertbefore='/usr/sbin'
      become: yes

    - hostname: name=svo-mac
      become: yes


  roles:

    - source-control
    - cli-tools
    - vim
    - python
    - system
    - java
    - gradle
    - maven
    - node
    - clojure
    - golang
    - kotlin
    - ruby
    - office
    - plantuml
    - atom
    - semgrep
    - security
    - internet
    - infrastructure-as-code
    - media
