- name: Add python3 as python to .zshrc
  lineinfile: dest=~/.zshrc line='alias python=python3' create=yes

- name: Add pip3 as pip to .zshrc
  lineinfile: dest=~/.zshrc line='alias pip=pip3'

- name: Install python setuptools
  pip: name=setuptools

- name: Install vim plugin
  git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
  with_items:
    - {repo: "https://github.com/python-mode/python-mode.git", dest: python-mode}
