- name: Install git source control
  homebrew: name=git

- name: Copy git-prompt.sh
  copy:
    src: "{{ item }}"
    dest: ~/.git-prompt.sh
    remote_src: yes
  with_fileglob: "/usr/local/Cellar/git/*/etc/bash_completion.d/git-prompt.sh"

- name: Setup git for zsh
  blockinfile:
    create: yes
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK (GIT)"
    block: |
      export GIT_PS1_SHOWDIRTYSTATE=1 GIT_PS1_SHOWSTASHSTATE=1 GIT_PS1_SHOWUNTRACKEDFILES=1
      export GIT_PS1_DESCRIBE_STYLE=branch
      export GIT_PS1_SHOWCOLORHINTS=1
      source ~/.git-prompt.sh
      precmd () { __git_ps1 "%n:%~" " $ " }

- name: Setup git colors
  blockinfile:
    path: ~/.gitconfig
    create: yes
    block: |
      [color]
        branch = auto
        diff = auto
        status = auto

      [color "branch"]
        current = yellow reverse
        local = yellow
        remote = green

      [color "diff"]
        meta = yellow bold
        frag = magenta bold
        old = red bold
        new = green bold

      [color "status"]
        added = yellow
        changed = green
        untracked = cyan
