- name: Install atom
  homebrew_cask: name=atom

- name: Setup additional bin path for atom
  blockinfile:
    create: yes
    path: ~/.atom/init.coffee
    block: |
      process.env.PATH = ["/usr/bin", "/usr/local/bin", ].join(":")
