- name: Install vim text editor
  homebrew: name=vim

- name: Setup paths for vim
  file: path={{ item }} state=directory
  with_items:
  - ~/.vim/autoload
  - ~/.vim/bundle
  - ~/.vim/ftplugin

- name: Install pathogen vim plugin/configuration manager
  get_url: url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim dest=~/.vim/autoload/pathogen.vim

- name: Install vim plugin
  git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }} force=yes
  with_items:
  - {repo: "https://github.com/scrooloose/nerdtree.git", name: nerdtree}
  - {repo: "https://github.com/Xuyuanp/nerdtree-git-plugin.git", name: nerdtree-git-plugin}
  - {repo: "https://github.com/ctrlpvim/ctrlp.vim.git", name: ctrlp}
  - {repo: "https://github.com/ntpeters/vim-better-whitespace.git", name: vim-better-whitespace}
  - {repo: "https://github.com/airblade/vim-gitgutter.git", name: vim-gitgutter}
  - {repo: "https://github.com/plasticboy/vim-markdown.git", name: vim-markdown}
  - {repo: "https://github.com/IN3D/vim-raml.git", name: vim-raml}
  - {repo: "https://github.com/Valloric/YouCompleteMe.git", name: YouCompleteMe}
  - {repo: "https://github.com/aklt/plantuml-syntax.git", name: plantuml-syntax}
  - {repo: "https://github.com/tfnico/vim-gradle.git", name: vim-gradle}
  - {repo: "https://github.com/python-mode/python-mode.git", name: python-mode}
  - {repo: "https://github.com/returntocorp/semgrep.vim.git", name: semgrep.vim}
  - {repo: "https://github.com/pangloss/vim-javascript.git", name: vim-javascript}

- name: Update .vimrc
  blockinfile:
    create: yes
    path: ~/.vimrc
    marker: "\" {mark} ANSIBLE MANAGED BLOCK"
    block: |
      execute pathogen#infect()
      syntax on
      filetype plugin indent on
      :set tabstop=2
      :set shiftwidth=2
      :set backspace=indent,eol,start
      :set expandtab
      :set nobackup
      :set noswapfile
      let g:ctrlp_map = '<c-p>'
      let g:ctrlp_cmd = 'CtrlP'
      autocmd BufEnter * EnableStripWhitespaceOnSave
      autocmd FileType Markdown setlocal spell spelllang=en_au
      set encoding=utf-8

- name: Install cmake
  homebrew: name=cmake

- name: Install YouCompleteMe
  shell: PATH=/usr/local/bin:$PATH ./install.sh chdir=~/.vim/bundle/YouCompleteMe
