- name: Install rbenv for ruby version management
  homebrew: name=rbenv

- name: Add rbenv to .zshrc
  lineinfile: dest=~/.zshrc line='eval "$(rbenv init -)"' create=yes

- name: Install ruby 3.2.0
  shell: rbenv install 3.2.0
