name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'


jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Remove existing setup
        run: |
          ./uninstall-homebrew.sh
          sudo rm -rf /Applications/Google\ Chrome.app

      - name: Provision
        run: |
          ./prepare.sh
          ./build.sh
        env:
          ANSIBLE_FORCE_COLOR: '1'

