name: Test

on: [push,pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run the default task
      run: |
        ./prepare.sh
        ./build.sh
